---
title: '"Introduction and spread of dengue virus 3 in Florida, United States, 2022" figures and statistics'
author: "Forrest Jones"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r functions}

source("code/R/functions.R")

```


```{r load-data}

source("code/R/load_data.R")

```


```{r}

arboNet_linelist_raw %>% filter(year<2022) %>% group_by(travel.status) %>% count(year) %>%
  summarize(median(n),
            max(n),
            min(n)
      )
```


## The Study


```{r}

as.numeric(end_date-start_date)/7

fdoh_linelist %>%
  summarize(
    n(),
    travelers=sum(travel.status=="Travel associated"),
    per_trav=mean(travel.status=="Travel associated"),
    local=sum(travel.status=="Locally acquired"),
    per_local=mean(travel.status=="Locally acquired")
  )

fdoh_linelist %>%
  count(denvserotype) %>%
  mutate(percent=round(n/sum(n)*100))


denv3_only %>%
  summarize(
    start=min(case_week),
    end=max(case_week)+6,
    weeks=as.numeric(end+1-start)/7,
    travelers=sum(travel.status=="Travel associated"),          local=sum(travel.status=="Locally acquired"),
    per_trav=mean(travel.status=="Travel associated"),
    white_n=sum(race=="White"),
    white_per=mean(race=="White"),
    ethnicity_n=sum(ethnicity=="Hispanic"),
    ethnicity_per=mean(ethnicity=="Hispanic")
  )
```



```{r}

denv3_only %>%
  filter(travel.status=="Travel associated") %>%
  summarize(
    n=n(),
  age= glue::glue("{median(age)} [{quantile(age,0.25)}-{quantile(age,0.75)}]"),
  male=mean(sex=="Male"),
  female=mean(sex=="Female"),
  n_cuba=sum(countryoforigin=="Cuba"),
  per_cuba=scales::percent(mean(countryoforigin=="Cuba")),
  per_miami=scales::percent(mean(County=="Miami-Dade")),
  n_miami=sum(County=="Miami-Dade"),
  n_counties = length(unique(County))
  )


# denv3_only %>%
#   filter(travel.status=="Travel associated") %>%
#   count(County) %>%
#   left_join(pop20) %>% 
#   mutate(ar=n/value*100000) %>%
#   select(County,n,value,ar) %>%
#   arrange(-ar)


# sequences %>%
#   filter(!is.na(`ZIP Code1 (Miami only)`)) %>%
#   distinct(`ZIP Code1 (Miami only)`) %>%
#   nrow()

denv3_only %>%
  filter(travel.status=="Locally acquired") %>%
  summarize(
    n=n(),
    male=mean(sex=="Male"),
  female=mean(sex=="Female"),
  age= glue::glue("{median(age)} [{quantile(age,0.25)}-{quantile(age,0.75)}]"),
  per_miami=scales::percent(mean(County=="Miami-Dade")),
  n_miami=sum(County=="Miami-Dade")
  
  )

denv3_only %>%
  filter(County=="Miami-Dade")%>%
  count()
  


```




## Figure 1

```{r}

p1a <- fdoh_linelist %>% 
  count(denvserotype,travel.status) %>%
  ggplot(aes(x=denvserotype,y=n,fill=fct_rev(travel.status)))+
    geom_col()+
  scale_fill_brewer("Case Type",
                    palette="Set1",direction = -1
                    )+
  theme_cowplot()+    
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  xlab("Dengue virus type")+
  ylab("Number\nof cases")


p1b <- denv3_only %>% 
  count(case_week,travel.status) %>%
  ggplot()+
  geom_col(aes(x=case_week,fill=fct_rev(travel.status),y=n))+
  scale_x_date("Week of Symptom Onset",
               date_labels = "%b %d, %Y",
               limits = as.Date(c("2022-05-01","2023-04-30")),
               date_breaks = "2 months"
               )+
  ylab("Number of\nDENV-3 cases")+
  scale_fill_brewer("Case Type",
                    palette="Set1",
                    direction=-1
                    )+
  cowplot::theme_cowplot()+
  theme(axis.text.x = element_text(angle = 45,hjust=1),
        legend.position = c(0.1,0.8)
        )






highcounties <- denv3_only %>%
  mutate(County=str_remove(County," County"))%>%
                  count(County) %>%
                  filter(n>=3)


travel_cases <- denv3_only %>%
  mutate(County=str_remove(County," County"))%>%
  mutate(new_country=ifelse(countryoforigin %in% c("Cuba","Unknown"),
                            countryoforigin,"Other Country"
                            )) %>%
  mutate(new_county=ifelse(County %in% highcounties$County,
                           County, "Other County"
                           ))%>%
   filter(travel.status=="Travel associated")%>%
   count(travel.status,new_county,new_country) %>%
   rename(case_type=new_country) 
  
local_cases <- denv3_only %>%
  mutate(County=str_remove(County," County"))%>%
  mutate(new_county=ifelse(County %in% highcounties$County,
                           County, "Other County"
                           ))%>%
   filter(travel.status=="Locally acquired")%>%
   count(travel.status,new_county) %>%
   mutate(case_type=travel.status)
  
plot_df <- bind_rows(travel_cases,local_cases)  %>%
      group_by(new_county)%>%
            mutate(total=sum(n)) %>%
            arrange(-total)

new_county_levels <- c(unique(plot_df$new_county)[unique(plot_df$new_county)!="Other County"],"Other County")


f1c <- plot_df %>%
  mutate(new_county=factor(new_county,levels=new_county_levels))%>%
  mutate(casetype_pretty=factor(case_type,
                                levels=c("Cuba","Other Country","Unknown","Locally acquired"),
                                labels=c("Traveled to\nCuba","Traveled to\nOther Country","Traveled to\nUnknown Country","No travel")
                                )
         )%>%
  ggplot(aes(x=casetype_pretty,y=fct_rev(new_county)))+
    geom_tile(aes(fill=travel.status,alpha=n))+
  geom_text(aes(label=n))+
  scale_alpha_continuous(trans="log10")+
  scale_fill_brewer(palette = "Set1")+
  theme_cowplot()+
  theme(#axis.text.x = element_text(angle=45,hjust=1),
                legend.position = "none"
        )+
  ylab("County")+
  xlab("Travel history")



f1_plot <- plot_grid(
  plot_grid(p1a+theme(legend.position = "right"),
          p1b+theme(legend.position = "none"),
          align = "hv", axis = "bt",rel_widths = c(0.5,0.5),
          labels=c("A","B")
          ) ,
  f1c, labels=(c("","C")),
  ncol=1,rel_heights = c(0.45,0.55)
)

f1_plot

ggsave("output/figure1.pdf",f1_plot,
       height = 4.81,
       width=6.48,
       scale = 1.4
       )


# 
# p1c <- denv3_only %>% 
#   count(travel.status,County) %>%
#   left_join(pop20) %>%
#   group_by(County) %>%
#   mutate(max_cases=max(n)) %>%
#   mutate(County=str_remove(County," County"))%>%
#   ggplot(aes(x=n,y=reorder(County,max_cases),fill=fct_rev(travel.status)))+
#     geom_col()+
#   scale_fill_brewer("Travel Status",
#                     palette="Set1",
#                     direction= -1
#                     )+
#   theme_cowplot()+
#   theme(legend.position = c(0.5,0.5))+
#   ylab("County")+
#   xlab("Number of DENV-3 cases")
# 
# p1d <- denv3_only %>% 
#   filter(travel.status=="Travel associated")%>%
#   count(countryoforigin) %>%
#   ggplot(aes(x=n,y=reorder(countryoforigin,n)))+
#     geom_col(fill=RColorBrewer::brewer.pal(n=3,"Set1")[2])+
#   theme_cowplot()+
#   ylab("Origin of travel")+
#   xlab("Number of travel associated DENV-3 cases")
# 
# 
# plot_grid(
#   plot_grid(p1a+theme(legend.position = "none"),
#           p1b+theme(legend.position = "none"),
#           align = "hv", axis = "bt",rel_widths = c(0.3,0.7),
#           labels=c("A","B")
#           ) ,
#   plot_grid(p1c,
#             p1d,
#             labels=c("C","D"),
#             rel_widths = c(0.5,0.5)
#             ),
#   ncol=1,rel_heights = c(0.45,0.55)
# )


```


## Discussion

```{r}


table(arboNet_linelist_raw$year,
      arboNet_linelist_raw$travel.status)



```


